#!/bin/sh
### BEGIN INIT INFO
# Provides: phony
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: phony telephony
# Description:
### END INIT INFO

case "$1" in
    start)
	echo "phony is starting"
	nohup /home/pi/coding/phony/phone/phony.py >/var/log/phony.log 2>&1 &
	;;
    stop)
	echo "phony is stopping"
	killall python
	;;
    *)
	echo "Usage: /etc/init.d/phony {start|stop}"
	exit 1
	;;
esac

exit 0

